[development]
address = "0.0.0.0"
port = 8000
workers = 8
log = "normal"
limits = { forms = 32768 }
secret_key = "IwX9iFv89wgZv7sExQwZhqQenAEvQaaAmpI1+rgoN40="

[production]
address = "0.0.0.0"
port = 8000
workers = 8
log = "normal"
limits = { forms = 32768 }
