export const ADD_PLAYER = 'ADD_PLAYER';
export const ADD_MATCH = 'ADD_MATCH';
export const RECEIVE_PLAYERS = 'RECEIVE_PLAYERS';
export const RECEIVE_MATCHES = 'RECEIVE_MATCHES';
export const RECEIVE_PLAYER_DETAIL = 'RECEIVE_PLAYER_DETAIL';
export const INVALIDATE_PLAYER_DETAIL = 'INVALIDATE_PLAYER_DETAIL';